### PR TITLE
Update glob in stable cicd action

### PR DESCRIPTION
**Pull request by jordanpadams**
Update that probably should have happened before merging #15 😨

### CODE REVIEW

**Review by nutjob4life — CHANGES_REQUESTED** [review]
I'm not sure this is a good idea. Help me understand what we're tying to help?

- `*` matches anything but `/`
- `**` matches anything including `/`

Suppose someone has a typo when they push a branch; they wanted `release/1.2.5` but typo'd `release/1.2/5`. If we keep the pattern `*`, then the workflow isn't triggered, you see what the problem is, and rename the branch.

But if the pattern is `**`, then the workflow is triggered, Roundup picks a wrong version number, things get pushed to artifact repositories, changelogs get generated, etc., and then there's a mess to clean up.

What am I missing? 🤔

**Comment by jordanpadams** [comment]
@nutjob4life oops! you are definitely right. please review again.

**Review by nutjob4life — APPROVED** [review]
🚢it!

**Comment by jordanpadams** [comment]
@nutjob4life feel free to merger these when you review them. Especially on projects you are closely tied to. 😎

**Comment by nutjob4life** [comment]
Okay, I will act with a bit more authority in the future @jordanpadams !

**Comment by jordanpadams** [comment]
@nutjob4life 🚔

**Pull request merged**
