### PR TITLE
Issue #25 - Add pytest and coverage support

### LINKED ISSUE #25: As a developer I want a powerful testing library included in our template repo
## 💪 Motivation
`pytest` provides us with useful introspection of failing tests, fixtures for managing test resources, and a large set of plugins we can easily leverage (like test coverage reports).

### PR DESCRIPTION
**Pull request by MJJoyce**
Add pytest and few a plugins for coverage, xdist for multi-core execution,
and continuous test watching / running.

Resolve #25

### CODE REVIEW

**Comment by jordanpadams** [comment]
@MJJoyce apologies if this is dumb question, but for existing python repos, will any updates be needed to existing tests to support these changes? or would this just be an update to their setup.cfg and magic?

**Comment by nutjob4life** [comment]
So `pytest` is the way to go instead of `tox`? I thought I read some place that `tox` was the _de facto_ way to run tests these days 🤷‍♀️

**Review by nutjob4life — APPROVED** [review]
👍

**Comment by MJJoyce** [comment]
> @MJJoyce apologies if this is dumb question, but for existing python repos, will any updates be needed to existing tests to support these changes? or would this just be an update to their setup.cfg and magic?

In my experience,`pytest` does a great job of picking up tests that it should run without any input. They claim that it works out of the box with common stuff on their site. Unless a repo is doing something out of the ordinary I don't think it'll be a problem.

> Can run unittest (including trial) and nose test suites out of the box

--

> So pytest is the way to go instead of tox? I thought I read some place that tox was the de facto way to run tests these days

It seems like people are trying to drag Python towards the frontend ecosystem world and it's support tool turnover cadence 
:). I don't regularly use `tox`, so I might not be the best to comment on it. However, I've seen `pytest` and `tox` run together in most (all?) situations where `tox` was being used. Not a huge sample size, but you can certainly run `pytest` through `tox`.  I wouldn't be opposed to adding `tox` into the loop but think doing 90% of the same thing via `pre-commit` in #27  probably isn't bad either.

**Comment by nutjob4life** [comment]
@MJJoyce `pytest` is fine with me

**Comment by MJJoyce** [comment]
Rebased to fix conflict in `setup.cfg`. Merging as is. Discussing `tox` stuff over in #29

**Pull request merged**
